Repository teamneoneko/Avatar-Toolkit, pull requests merged in 2024-07, with the labels that each got.

#24 Add Fbx import
  __init__.py
  core/__init__.py
  core/importer.py
  core/pmd/import_pmd.py
  core/pmx/import_pmx.py
  core/properties.py
  core/register.py
  functions/translations.py
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  ui/__init__.py
  ui/quick_access.py
  ui/settings.py
Labels: Completed

#22 Start of Translations
  __init__.py
  core/addon_preferences.py
  core/export_resonite.py
  core/properties.py
  core/register.py
  functions/combine_materials.py
  functions/join_meshes.py
  functions/resonite_functions.py
  functions/translations.py
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  ui/optimization.py
  ui/panel.py
  ui/quick_access.py
  ui/settings.py
  ui/tools.py
Labels: Completed

#26 Remove doubles
  .gitignore
  .vscode/settings.json
  functions/remove_doubles_safely.py
  ui/optimization.py
  ui/tools.py
Labels: Completed

#30 Basic Start of Armature Selection
  core/common.py
  core/properties.py
  functions/combine_materials.py
  functions/join_meshes.py
  functions/remove_doubles_safely.py
  functions/resonite_functions.py
  ui/optimization.py
  ui/quick_access.py
  ui/tools.py
Labels: Feature, Completed

#33 Import anything
  core/common.py
  core/dictionaries.py
  core/importer.py
  core/preferences.json
  core/register.py
  functions/import_anything.py
  resources/translations/en_US.json
  ui/quick_access.py
Labels: Feature, Completed

#32 Digitigrade legs tool
  core/common.py
  functions/digitigrade_legs.py
  ui/tools.py
Labels: Feature, Completed

#27 Visemes Creation
  core/common.py
  core/properties.py
  functions/viseme.py
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  ui/viseme.py
Labels: Initial Work Done

#34 Texture Atlasing hot fix
  __init__.py
  core/common.py
  core/properties.py
  functions/atlas_materials.py
  ui/atlas_materials.py
Labels: bug, Completed

#38 Improvements
  core/common.py
  core/properties.py
  functions/combine_materials.py
  functions/import_anything.py
  functions/join_meshes.py
  functions/translations.py
  functions/viseme.py
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  ui/atlas_materials.py
  ui/optimization.py
  ui/panel.py
  ui/quick_access.py
  ui/settings.py
  ui/tools.py
  ui/viseme.py
Labels: enhancement, Feature, Completed
