Repository teamneoneko/Avatar-Toolkit, pull requests merged in 2024-09, with the labels that each got.

#50 Fix pmd and pmx importing somewhat
  core/import_pmd.py
  core/import_pmx.py
Labels: Work In Progress

#53 Report to user what we done.
  functions/combine_materials.py
  resources/translations/en_US.json
Labels: enhancement

#57 Rigify To Unity Function
  core/properties.py
  functions/rigify_functions.py
  resources/translations/en_US.json
  ui/tools.py
Labels: enhancement, Feature

#55 Connect Bones
  functions/additional_tools.py
  resources/translations/en_US.json
  ui/tools.py
Labels: enhancement, Feature, Completed

#56 Remove Bone constraints
  functions/additional_tools.py
  resources/translations/en_US.json
  ui/tools.py
Labels: enhancement, Feature, Completed

#59 Quick Fix to Apply shapeky to basis in init.py
  __init__.py
  functions/mesh_tools.py
Labels: bug, Completed

#62 Update README.md
  README.md
Labels: Completed
