Repository teamneoneko/Avatar-Toolkit, pull requests merged in 2025-04, with the labels that each got.

#147 Move simpify_bonename to dictionaries
  core/common.py
  core/dictionaries.py
Labels: Completed

#153 Read me update.
  README.md
Labels: documentation, Completed

#154 Vastly improve Merge Doubles
  functions/optimization/remove_doubles.py
  resources/translations/en_US.json
  ui/optimization_panel.py
Labels: enhancement, Completed

#155 Add Explode Model
  functions/tools/general_mesh_tools.py
  resources/translations/en_US.json
  ui/tools_panel.py
Labels: Feature, Completed

#156 PMX Import - First Stage
  core/importers/importer.py
  core/lamp.py
  core/mmd/__init__.py
  core/mmd/bpyutils.py
  core/mmd/core/__init__.py
  core/mmd/core/bone.py
  core/mmd/core/camera.py
  core/mmd/core/exceptions.py
  core/mmd/core/lamp.py
  core/mmd/core/material.py
  core/mmd/core/model.py
  core/mmd/core/morph.py
  core/mmd/core/pmx/__init__.py
  core/mmd/core/pmx/importer.py
  core/mmd/core/rigid_body.py
  core/mmd/core/sdef.py
  core/mmd/core/shader.py
  core/mmd/core/translations.py
  core/mmd/core/vmd/__init__.py
  core/mmd/core/vmd/importer.py
  core/mmd/cycles_converter.py
  core/mmd/operators/__init__.py
  core/mmd/operators/material.py
  core/mmd/operators/misc.py
  core/mmd/operators/model.py
  core/mmd/operators/model_edit.py
  core/mmd/operators/morph.py
  core/mmd/operators/rigid_body.py
  core/mmd/operators/sdef.py
  core/mmd/operators/translations.py
  core/mmd/operators/view.py
  core/mmd/properties/__init__.py
  core/mmd/properties/material.py
  core/mmd/properties/morph.py
  core/mmd/properties/pose_bone.py
  core/mmd/properties/rigid_body.py
  core/mmd/properties/root.py
  core/mmd/properties/translations.py
  core/mmd/translations.py
  core/mmd/utils.py
  cycles_converter.py
Labels: Feature, Completed

#158 Logging update
  __init__.py
  core/auto_load.py
  core/logging_setup.py
  core/properties.py
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  ui/settings_panel.py
Labels: enhancement, Completed

#159 Mmd tools improvements
  blender_manifest.toml
  core/armature_validation.py
  core/lamp.py
  core/mmd/bpyutils.py
  core/mmd/core/bone.py
  core/mmd/core/camera.py
  core/mmd/core/lamp.py
  core/mmd/core/material.py
  core/mmd/core/model.py
  core/mmd/core/morph.py
  core/mmd/core/pmx/importer.py
  core/mmd/core/rigid_body.py
  core/mmd/core/sdef.py
  core/mmd/core/shader.py
  core/mmd/cycles_converter.py
  core/mmd/operators/material.py
  core/mmd/operators/misc.py
  core/mmd/operators/model.py
  core/mmd/operators/model_edit.py
  core/mmd/operators/morph.py
  core/mmd/operators/rigid_body.py
  core/mmd/operators/sdef.py
  core/mmd/operators/view.py
  core/mmd/properties/material.py
  core/mmd/properties/morph.py
  core/mmd/properties/pose_bone.py
  core/mmd/properties/rigid_body.py
  core/mmd/properties/root.py
  core/mmd/translations.py
  core/mmd/utils.py
  core/updater.py
  cycles_converter.py
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  ui/quick_access_panel.py
Labels: enhancement, Completed
